# Generated by Django 3.2.10 on 2023-03-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='categories',
            field=models.ManyToManyField(to='brand.Categories'),
        ),
    ]
