# Generated by Django 4.1.7 on 2023-03-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0002_city_country_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='main_category',
            field=models.CharField(choices=[('Cultivarea cerealelor, porumbului si a altor plante', 'Cultivarea cerealelor, porumbului si a altor plante'), ('Cultivarea legumelor, a specialitatilor horticole si a produselor de sera', 'Cultivarea legumelor, a specialitatilor horticole si a produselor de sera'), ('Cultivarea fructelor, nucilor, a plantelor pentru bauturi si mirodenii', 'Cultivarea fructelor, nucilor, a plantelor pentru bauturi si mirodenii'), ('Cresterea animalelor, activitatea fermelor pentru obtinerea laptelui', 'Cresterea animalelor, activitatea fermelor pentru obtinerea laptelui'), ('Cresterea ovinelor, caprinelor, cabalinelor, magarilor, catarilor si asinilor', 'Cresterea ovinelor, caprinelor, cabalinelor, magarilor, catarilor si asinilor')], max_length=105),
        ),
    ]
