# Generated by Django 4.1.7 on 2023-03-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0005_alter_brand_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='country',
            field=models.CharField(choices=[('Andorra', 'Andorra'), ('Emiratele', 'Emiratele'), ('Afganistan', 'Afganistan'), ('Antigua', 'Antigua'), ('Anguilla', 'Anguilla')], max_length=50),
        ),
    ]
