# Generated by Django 4.1.7 on 2023-03-13 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0007_alter_brand_city_alter_brand_country'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
