# Generated by Django 4.1.7 on 2023-03-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0009_alter_brand_main_category_alter_brand_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='main_category',
            field=models.CharField(choices=[('Administratie / Sector Public', 'Administratie / Sector Public'), ('Agricultura / Silvicutura / Pescuit', 'Agricultura / Silvicutura / Pescuit')], max_length=105),
        ),
        migrations.AlterField(
            model_name='brand',
            name='type',
            field=models.CharField(choices=[('initial', 'Brand comercial'), ('O', 'ONG')], max_length=20),
        ),
    ]
