# Generated by Django 4.1.7 on 2023-03-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0010_alter_brand_main_category_alter_brand_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='type',
            field=models.CharField(choices=[('Brand comercial', 'Brand comercial'), ('O', 'ONG')], max_length=20),
        ),
    ]
