# Generated by Django 4.1.7 on 2023-03-13 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0013_alter_brand_founding_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='categories',
            field=models.CharField(blank=True, choices=[('Administratie / Sector Public', 'Administratie / Sector Public'), ('Agricultura / Silvicutura / Pescuit', 'Agricultura / Silvicutura / Pescuit')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='main_category',
            field=models.CharField(choices=[('Administratie / Sector Public', 'Administratie / Sector Public'), ('Agricultura / Silvicutura / Pescuit', 'Agricultura / Silvicutura / Pescuit')], max_length=50),
        ),
    ]
