# Generated by Django 4.1.7 on 2023-03-18 20:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0030_brand_cover_brand_logo_alter_brand_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 18, 22, 18, 43, 698853)),
        ),
        migrations.AlterField(
            model_name='brand',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 18, 22, 18, 43, 698853)),
        ),
    ]
