# Generated by Django 4.1.7 on 2023-03-19 07:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0035_alter_brand_created_at_alter_brand_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 19, 9, 29, 11, 64302)),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(error_messages={'required': 'Adauga numele brandului!'}, max_length=64),
        ),
        migrations.AlterField(
            model_name='brand',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 19, 9, 29, 11, 64302)),
        ),
    ]
