# Generated by Django 4.1.7 on 2023-03-19 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0037_alter_brand_created_at_alter_brand_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='updated_at',
        ),
    ]
