# Generated by Django 4.1.7 on 2023-03-19 10:54

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0039_alter_brand_description_alter_brand_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='description',
            field=djrichtextfield.models.RichTextField(),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(default='media/images/eviasoft.jpg', upload_to='images/'),
        ),
    ]
