# Generated by Django 4.1.7 on 2023-03-19 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0041_alter_brand_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='logo',
        ),
    ]
