# Generated by Django 4.1.7 on 2023-03-19 11:29

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0042_remove_brand_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='description',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
