# Generated by Django 3.2.10 on 2023-03-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0043_alter_brand_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='description',
            field=models.TextField(),
        ),
    ]
