# Generated by Django 3.2.10 on 2023-03-19 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0044_alter_brand_description'),
    ]

