# Generated by Django 3.2.10 on 2023-03-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0049_alter_brand_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='categories',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
