# Generated by Django 3.2.10 on 2023-03-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0050_alter_brand_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='terms',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
