# Generated by Django 3.2.10 on 2023-03-21 20:50

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0057_alter_brand_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=cloudinary.models.CloudinaryField(default=3, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
