# Generated by Django 3.2.10 on 2023-03-23 20:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0063_alter_brand_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='cover',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='cover'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='logo'),
        ),
    ]
