# Generated by Django 3.2.10 on 2023-03-24 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0064_auto_20230323_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='logo',
        ),
    ]
