# Generated by Django 3.2.10 on 2023-03-24 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0065_auto_20230324_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='description',
        ),
    ]
