# Generated by Django 3.2.10 on 2023-03-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0072_alter_brand_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('Administratie / Sector public', 'Administratie / Sector public'), ('Agricultura / Silvicultura / Pescuit', 'Agricultura / Silvicultura / Pescuit'), ('Arhitectura / Design', 'Arhitectura / Design'), ('Arta / Cultura / Recreatie', 'Arta / Cultura / Recreatie'), ('Auto & Moto', 'Auto & Moto'), ('Banci, Asigurari & Servicii financiare', 'Banci, Asigurari & Servicii financiare'), ('Call centre / BPO', 'Call centre / BPO'), ('Comert / Retail', 'Comert / Retail'), ('Confectii', 'Confectii'), ('Constructii', 'Constructii'), ('Consultanta', 'Consultanta'), ('Domeniul Alimentar', 'Domeniul Alimentar'), ('Domeniul chimic', 'Domeniul chimic'), ('Domeniul farmaceutic', 'Domeniul farmaceutic'), ('Drept / Legislatie', 'Drept / Legislatie'), ('Educatie / Cercetare / Training', 'Educatie / Cercetare / Training'), ('Fashion / Textile', 'Fashion / Textile'), ('Frumusete & Ingrijire', 'Frumusete & Ingrijire'), ('Imobiliare', 'Imobiliare'), ('IT / Telecom & Comunicatii', 'IT / Telecom & Comunicatii'), ('Lemn / PVC', 'Lemn / PVC'), ('Media / Marketing & Publicitate', 'Media / Marketing & Publicitate'), ('Medicina / Sanatate & Asistenta sociala', 'Medicina / Sanatate & Asistenta sociala'), ('Petrol / Gaze / Energie', 'Petrol / Gaze / Energie'), ('Prestari alte servicii', 'Prestari alte servicii'), ('Prestari servicii / Liber profesionisti', 'Prestari servicii / Liber profesionisti'), ('Productie', 'Productie'), ('Protectia mediului', 'Protectia mediului'), ('Protectie & Paza', 'Protectie & Paza'), ('Sport', 'Sport'), ('Transport / Logistica', 'Transport / Logistica'), ('Turism / Horeca', 'Turism / Horeca')], max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='brand',
            name='categories',
        ),
        migrations.AddField(
            model_name='brand',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='brand.Categories'),
        ),
    ]
