# Generated by Django 3.2.10 on 2023-03-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0073_auto_20230324_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='categories',
            field=models.ManyToManyField(blank=True, choices=[], null=True, to='brand.Categories'),
        ),
    ]
