# Generated by Django 3.2.10 on 2023-03-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0075_auto_20230324_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='categories',
        ),
        migrations.AddField(
            model_name='brand',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='brand.Categories'),
        ),
    ]
