# Generated by Django 3.2.10 on 2023-03-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0076_auto_20230324_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='categories',
            field=models.ManyToManyField(to='brand.Categories'),
        ),
    ]
