# Generated by Django 3.2.10 on 2023-03-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0081_auto_20230324_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='categories',
        ),
        migrations.AddField(
            model_name='brand',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='brand.Categories'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
