# Generated by Django 4.1.7 on 2023-03-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_remove_message_author_message_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='phone',
            field=models.CharField(default='Add phone ', max_length=12),
        ),
    ]
