# Generated by Django 4.1.7 on 2023-03-06 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_message_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='phone',
            field=models.CharField(default='', max_length=12),
        ),
    ]
