# Generated by Django 4.1.7 on 2023-03-09 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_newsletter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='user',
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
