# Generated by Django 4.1.7 on 2023-03-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_remove_newsletter_user_alter_newsletter_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
    ]
