# Generated by Django 4.1.7 on 2023-03-09 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_newsletter_name_alter_newsletter_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter',
        ),
    ]
